### ISSUE TITLE
Allow objects when using multiple arguments

### ISSUE THREAD

**Issue by leoasis** [petehunt/react-classset#4]
It would be nice to treat plain object arguments the same way as when used as a single argument, when they are passed along with strings or other values. That way we can pass strings for class names that are always true, and an object just for things that are conditionally rendered.

Example:

``` js
var className = cx({
  button: true,
  'button-primary': type == 'primary'
});

// This would be equivalent to the previous one:
var className = cx('button', {'button-primary: type == 'primary'});
```

If you think this makes sense, I can submit a PR with this, just wanted to know if you though about some issues beforehand with this approach.

**Comment by chenglou** [comment]
Lol, then this library becomes almost exactly this: https://github.com/JedWatson/classnames

Which is the other one the React classSet doc page will recommend (https://github.com/facebook/react/pull/2994)

I think we should just unify these two libs. I'll handle it.

**Comment by leoasis** [comment]
Yeah haha I saw that you forked that one on my activity feed right after
submitting this one, and it provides just that. Great then!

**Comment by tleunen** [comment]
Well, if another lib already exists and does exactly the same thing, why did you recreate one?

**Comment by chenglou** [comment]
@tleunen because this one actually came first =)
